name: Build UMP

on:
  [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64", "x86_64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
        
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y meson libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-drm-${{matrix.arch}} >build-crossfile-drm
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../build-crossfile-drm" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=enabled \
            -Dvc4=disabled \
            -Detnaviv=disabled \
            -Dfreedreno-kgsl=true
          ninja -C "build-android" install
          cd ..
          envsubst <android-${{matrix.arch}} >build-crossfile
          meson setup "build-android" \
            --prefix=/tmp/mesa \
            --cross-file "build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=25 \
            -Dandroid-stub=true \
            -Dandroid-libbacktrace=disabled \
            -Dandroid-strict=false \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=freedreno,zink,panfrost \
            -Dfreedreno-kmds=kgsl \
            -Dshared-glapi=false \
            -Dbuildtype=release
          ninja -C "build-android" install
          envsubst <android-turnip-${{matrix.arch}} >build-crossfile-turnip
          meson setup "build-android-turnip" \
            --cross-file "build-crossfile-turnip" \
            -Dbuildtype=release \
            --prefix=/tmp/mesa \
            -Dplatforms=android \
            -Dplatform-sdk-version=33 \
            -Dandroid-stub=true \
            -Dgallium-drivers= \
            -Dvulkan-drivers=freedreno \
            -Dfreedreno-kmds=kgsl \
            -Dandroid-strict=false \
            -Db_lto=true
          ninja -C "build-android-turnip" install
          mkdir /tmp/mesa/toupload
          mv /tmp/mesa/lib/libOSMesa.so.8.0.0 /tmp/mesa/lib/libvulkan_freedreno.so /tmp/mesa/toupload/
          cd /tmp/mesa/toupload
          mv libOSMesa.so.8.0.0 libOSMesa.so
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: UMP_${{matrix.arch}}
          path: /tmp/mesa/toupload
